### PR TITLE
WS healthcheck automation

### PR DESCRIPTION
**Pull request by Tsunghao-C**
## 2024/12/14 update
In order to avoid accidental WS collapse in future PRs, I added a script to test the WS healthiness of game and chat services.

So now in addition to check if all containers are running without restart, it will also run a script to test the entrypoint of web socket for /ws/game-server/ and /ws/chat-server/ respectively.

These WS testing relies on **dedicated health_test entrypoint** for chat and game respectively. ** Please Make sure to keep the following settings untouched: **
1. Chat service
  - WebSocket endpoint: /ws/health/chat/
  - routing.py: `re_path(r"^ws/health/chat/$", consumers.ChatHealthConsumer.as_asgi()), # Health check endpoint`
  - consumers.py: the class `ChatHealthConsumers`
2. Game service
  - WebSocket endpoint: /ws/health/game/
  - routing.py: `re_path(r"^ws/health/game/$", consumers.GameHealthConsumer.as_asgi()), # Health check endpoint`
  - consumers.py: the class`GameHealthConsumers`

### How it works

1. After checking all services are running healthily, WS check comes immediately 
2. The WS test uses the bash scripts in pong-game/tests to run the tests, so the dependencies will be the host machine `python` version and `websockets` version. (Since we know that the school computer's websockets version is too out of date, I also added a prepare script to use compatible websockets version. In production mode, it is the web browser to create WS, so it won't be out of date)
3. The WS health check uses **python** and **websockets** to directly build WS connection to server and interact with the backend logic in **consumers.py**. So we don't need to keep html files in the templates actually.
4. I created dedicated Consumer class and entrypoint for health check, so it won't affect the production parts.

### What to expect

When you run `make` or `make check` you shall see:
1. Everything work fine. (If backend servers aren't ready, it will return 502, and it will retry up to 3 times)
Screenshot 2024-12-14 at 22 08 38

2. One of the WS is failed after 3 retries (Maybe the WS url pattern is missing)
Case 3_Missing WS urlpatterns

3. Both WS are not working after 3 retries (Maybe WS socket server setting is broken)
Case 2_Missing Daphne

5. Direct WS error message (Could be Wrong routing setting)
Case 1_Wrong ws routing setting

### CODE REVIEW

**Review by Haliris — CHANGES_REQUESTED** [review]
The semantics I use in game_test.html to communicate with the servers are different, so I'll need this file to be updated to run tests at some point. I can get around to doing that when I finish things on my branch later.

**Comment by Tsunghao-C** [comment]
> The semantics I use in game_test.html to communicate with the servers are different, so I'll need this file to be updated at some point. I can get around to doing that when I finish things on my branch later.

I think you misunderstand something. The game_test.html I mentioned is only used for WS_check script to check if WS can be built. You should work on your own html test files or even create new ones with its dedicated paths and views to serve and be responsible for the routing logic. 

What I need is to keep the WS_health check test files as they are. The test script won't test other operational html files.

**Comment by Atwazar** [comment]
image


works for me, waiting for the game de vapproval

**Review by Haliris — DISMISSED** [review]
Lifting the block now that we figured out the issue with the consumer. Let me know if you need help with a solution

Still do not merge until tsunghao is ready

**Comment by Tsunghao-C** [comment]
Updated PR explanations. Now it is ready to merge and won't affect production part backend logic.

**Review by BenjaminHThomas — APPROVED** [review]
lgtm

**Pull request merged**
