### PR TITLE
Saving games issues

### PR DESCRIPTION
**Pull request by Atwazar**
Now game issues are saved and mmr are updated which are triggering the leaderboard to be udpated as well

also i've corrected an issue with solo games where the data was set up weirdly, making it work again.

Finally there's a game type data that is set in the consumer 
game_type = {
			"is_online": False,
			"is_local": False,
			"is_ai": True
		}
We are using this in game room to know if issue is to be saved or not, 
We should use it in the future to set up the ai player, 
and for local games and ai games to just update the ready status... actually it's not that long i'll do it right away

### CODE REVIEW

**Comment by Atwazar** [comment]
Changes mention are done, tho ben had already made some clean function to save mmr, mine can be erased without problems

**Review by Haliris — DISMISSED** [review]

**Comment by Atwazar** [comment]
I'm still f'in bad at merging, contact me if errors.

**Comment by Atwazar** [comment]
This is merged in another PR

**Comment by Atwazar** [comment]
closing pr

**Pull request closed without merging**
