### PR TITLE
Local tournament

### PR DESCRIPTION
**Pull request by Atwazar**
Local tournament Skeleton is up, 
you can create a tournament. Then clicking on "afficher le prochain match" create the next game instance.
If it's ai vs ai, the game is played and winner is set randomly according to the ai difficulty, here's the associated tab :
    const probabilities = {
        'hard': { 'easy': 0.75, 'medium': 0.67, 'hard': 0.50 },
        'medium': { 'easy': 0.67, 'medium': 0.50, 'hard': 0.33 },
        'easy': { 'easy': 0.50, 'medium': 0.33, 'hard': 0.25 }
    };
    (to help you read it here's an exemple : an hard ai has 75% chance to win vs easy, 67% vs meidum and 50% vs hard
Else the game can be started by clicking on ready.

there's an issue at the moment when you try to start the next game, as well as bracket display is not updated correcty.
Refreshing the page is now the solution for this problem, they should be fix in a next PR.

closes https://github.com/Tsunghao-C/ft_Transcendence/issues/95

closes https://github.com/Tsunghao-C/ft_Transcendence/issues/102

### CODE REVIEW

**Comment by Atwazar** [comment]
I added colors to the tournament, just a bit, 
I finally fixed the consummer by using only id to prevent weird scenarios.
I cleaned the vent listenners before adding new ones

**Comment by Atwazar** [comment]
#95 and #102 should be close

**Comment by Haliris** [comment]
Syntax is:

closes #95 

closes #102

**Review by Haliris — APPROVED** [review]
Fixed

**Comment by Atwazar** [comment]
just merging main.
Also i cleaned a bit the lobby and the queue.
Now quitting the lobby should not make anything explode.
Same with the queue, plus there's a timer now, so people can watch something move as they are waiting in the queue

**Review by Tsunghao-C — DISMISSED** [review]
The local tournament works pretty well. Good job.

There is a weird error that happened only when we first do the tournament after application launch (by `make` or `make re`). I documented in issue #110 

But in general, this is a big progress on tournament feature and I am okay to approve this PR first.

ELK part merges well and works fine.

**Review by Tsunghao-C — APPROVED** [review]
This updates improve the issue #110 , but I still got an error till the end of first tournament.

Approve this PR first and I will update issue separately.

**Pull request merged**
