### PR TITLE
Game menu

### PR DESCRIPTION
**Pull request by Atwazar**
This is an upgrade of friends, chat and menu.
All of them are, with this pr, working in the url just like the profile does.
The game is accessible in the front end via game->multiplayer->online->join a room. This is basically the file from the backend at the moment, i intend on making it functionnal with players tomorrow.
I've finally patch the weird subliminal redirection at every changes. 
A bunch of refresh should be better now, like in chat. 

I still have an issue in chat when we try to send a message to a player, it will not redirect to /private/nananan when we type his alias.

Chat rooms named are not changed at the moment.

### CODE REVIEW

**Comment by Atwazar** [comment]
Oh and i forgot to mention i deleted the game files that were still in the front, Jean you need to check if it's ok with you, i might have done some extra cleaning.

**Comment by Haliris** [comment]
> Oh and i forgot to mention i deleted the game files that were still in the front, Jean you need to check if it's ok with you, i might have done some extra cleaning.

I have no use for these files, they are documented here anyway in case we need them for some reasons.

**Review by Haliris — DISMISSED** [review]
Just some notes going forward

**Comment by Atwazar** [comment]
oh and i added this verification 
if (page.startsWith("profile/")) {
						if (page.split("/").length > 2) {
							set404View(innerContent);
						}
						const profileUsername = page.split("/")[1] || data.alias;
						setProfileView(innerContent, profileUsername);
					} else if (page.startsWith("chat/")) {
						const pageSplit = page.split("/");
						if (pageSplit.length > 3) {
							set404View(innerContent);
						} else {
							const roomType = page.split("/")[1];
							if (roomType) {
								const aliasOrRoomToJoin = page.split("/")[2];
								if (!['public', 'private'].includes(roomType)) {
									set404View(innerContent);
								} else if (aliasOrRoomToJoin) {
									setChatView(innerContent, roomType, aliasOrRoomToJoin);
								} else {
									setChatView(innerContent);
								}
							} else {
								if (page.split("/").length > 2) {
									set404View(innerContent);
								} else {
									setChatView(innerContent);
								}
							}
						} 
						
						Wich i feel like it's a very clunky logic, i've done it pretty late, i think some changes will need to be made, 
						It's like to prevent url like /chat//alias to work

**Review by Tsunghao-C — APPROVED** [review]
The remote gameplay via frontend works well. And indeed you can't copy the room_id right now which is a cool "feature".

In the future, maybe the room_id is not needed to copy and paste but directly create a link for the other player if the player is invited.

**Pull request merged**
