### PR TITLE
New branch for chat

### PR DESCRIPTION
**Pull request by Atwazar**
Public room chat is working, 

I had to comment some of your code to make it work in routings and url Tsunghao. 

You can now : create and join public room.
see the messages previously sent on this rooms. 
click on someone else profile to get redirected to its page.

to had next :
mandatory :
Having the block function actually blocking messages.
creating links to gaming room
tournaments creating a specific room to send messages of futures matchs
could do :
make a view to access all messages available
private message 
adding the chat you're in to the url so like profile does so you can navigate more easily
create per default a general room

### CODE REVIEW

**Comment by Tsunghao-C** [comment]
I did the following tests:
1. Create a user and create a public chat room
2. Enter the chat room and it works.
3. Second user can enter an already existing chat room.

However, there are several issues:
1. If you refresh the webpage at chat tab, it will cause errors
2. If a username is different to user alias, the chatroom won't work

**Comment by Atwazar** [comment]
woups i pushed on the wrong branch... 
do not merge untill im done then

**Comment by nyzss** [comment]
LGTM 👍

**Comment by Atwazar** [comment]
Ive added a lot of new stuff int there, Mostly now you have the chat that is kinda of done and working. 
You ca send direct private message to user
You have now the button send message from the profile view and friend view that should be working, blocked user are supposed to be block..

If you guys could make some checks regarding differents stuff and identiy inconsistencies, ill chekc and clean tomorrow anyway. 
I know that :
The private messsage room name display is trash
Some weirf interaction when you try to send a message to a block user i think.

**Comment by Atwazar** [comment]
Oh and yeah i think i need to add a field for the messages to know if its like an invite for later

**Comment by Atwazar** [comment]
this merge should probably be reverted 
https://github.com/Tsunghao-C/ft_Transcendence/pull/61/commits/e65a16d05a395bceb578e97a6f84edcd9251a4ea
I dont really know how to merge them properly without destroying tsung haos work

**Comment by Tsunghao-C** [comment]
Okay, I will revert and merge it again for you.

**Pull request closed without merging**
